// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBw9eVnU0Xj16ZCalCB4SYWAeIB2p6Yxx4',
    appId: '1:690861600563:web:8de20a0fb0839651225846',
    messagingSenderId: '690861600563',
    projectId: 'reducer-3e8dc',
    authDomain: 'reducer-3e8dc.firebaseapp.com',
    storageBucket: 'reducer-3e8dc.firebasestorage.app',
    measurementId: 'G-DZLZEKBBFN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_KOvmSGFqOdB_z3HbxfwCeCyW1NOKrNw',
    appId: '1:690861600563:android:5ff13dd72cabf74b225846',
    messagingSenderId: '690861600563',
    projectId: 'reducer-3e8dc',
    storageBucket: 'reducer-3e8dc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUn9JI0BXTOIFnex1-N-a__GtQ10di28M',
    appId: '1:690861600563:ios:1b6b14877f4b0114225846',
    messagingSenderId: '690861600563',
    projectId: 'reducer-3e8dc',
    storageBucket: 'reducer-3e8dc.firebasestorage.app',
    iosBundleId: 'com.tarurinfotech.reducer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUn9JI0BXTOIFnex1-N-a__GtQ10di28M',
    appId: '1:690861600563:ios:1b6b14877f4b0114225846',
    messagingSenderId: '690861600563',
    projectId: 'reducer-3e8dc',
    storageBucket: 'reducer-3e8dc.firebasestorage.app',
    iosBundleId: 'com.tarurinfotech.reducer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBw9eVnU0Xj16ZCalCB4SYWAeIB2p6Yxx4',
    appId: '1:690861600563:web:67c6e268a486c7ea225846',
    messagingSenderId: '690861600563',
    projectId: 'reducer-3e8dc',
    authDomain: 'reducer-3e8dc.firebaseapp.com',
    storageBucket: 'reducer-3e8dc.firebasestorage.app',
    measurementId: 'G-8MLT1EJ1GB',
  );
}

